version: '3.1'
services:
  nginx-gateway:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./config/nginx/logs:/var/log/nginx
      - ./config/nginx/html:/usr/share/nginx/html
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      TZ: Asia/Shanghai
    # networks:
    #   - nginx-gateway

# networks:
#   nginx-gateway:
#     driver: bridge
